stages:
  - test
  - build

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    PIPENV_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pipenv"


cache:
  key: pip
  paths:
    - $CI_PROJECT_DIR/.cache/pip
    - $CI_PROJECT_DIR/.cache/pipenv

test:
  stage: test
  image: python:3.8-slim
  script:
    - pip install pipenv flake8 pytest-cov
    - pipenv install --system --dev
    - flake8
    - pytest --cov=qualle


test_safety:
  stage: test
  image: python:3.8-slim
  script:
    - pip install pipenv safety==1.10.*
    - pipenv install --system --dev
    - safety check --full-report
  rules:
    - changes:
      - Pipfile*
  allow_failure: true


build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - set +x
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - set -x
    - /kaniko/executor --build-arg PIP_INDEX_URL=$PIP_INDEX_URL --build-arg PIPENV_PYPI_MIRROR=$PIPENV_PYPI_MIRROR --reproducible --cache=true --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE/qualle:$CI_COMMIT_REF_SLUG --cleanup
  rules:
    - if: '$CI_COMMIT_TAG'
