[tool.poetry]
name = "qualle"
version = "0.2.0-dev"
description = "A framework to predict the quality of a multi-label classification result"
authors = ["AutoSE <autose@zbw.eu>"]
license = "Apache-2.0"
readme = "README.md"
classifiers = [
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Artificial Intelligence"
]
homepage = "https://github.com/zbw/qualle"

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
scikit-learn = "~0.24"
stwfsapy = "==0.1.5"
scipy = "~1.6"
rdflib = "~4.2"
pydantic = ">=1.8.2,<1.9"
fastapi = "~0.66"
uvicorn = ">=0.14,<0.15"


[tool.poetry.group.dev.dependencies]
pytest = "~6.2"
pytest-mock = "~3.5"
pytest-cov = "~3.0"
requests = "~2.25"
flake8 = "~3.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
qualle = 'qualle.interface.cli:cli_entrypoint'